/* Static review: feedback never leaves the browser until the participant exports it. */
(async()=>{
 const $=s=>document.querySelector(s);
 const escape=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
 let data;
 try{const r=await fetch('review.json');if(!r.ok)throw Error('HTTP '+r.status);data=await r.json();}catch{ $('#frames').textContent='Не удалось загрузить материалы. Обновите страницу.';return;}
 const key='jewelsnap-review:'+data.version;let state={};let storageOK=true;
 try{const saved=JSON.parse(localStorage.getItem(key)||'{}');if(saved&&typeof saved==='object'&&!Array.isArray(saved))state=saved;}catch{storageOK=false;}
 const val=(k,f)=>typeof state[k]?.[f]==='string'?state[k][f]:'';
 const save=()=>{try{localStorage.setItem(key,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}$('#storage-status').textContent=storageOK?'Черновик сохранён в этом браузере. Чтобы поделиться — скопируйте решения.':'Браузер не сохраняет черновик. Скопируйте или скачайте решения до закрытия страницы.';};
 $('#version').textContent=data.version;
 const shot=(id,label,isNew)=>`<figure class="shot ${isNew?'new':''}"><figcaption>${id} · ${label}</figcaption><button class="image-button" data-image="${id}" aria-label="Увеличить ${id}"><img loading="lazy" width="440" height="956" src="previews/${id}.jpg" alt="${id} — ${label}"></button></figure>`;
 $('#new-series').innerHTML=data.frames.map(f=>shot(f.id,'Студия',true)).join('');
 $('#frames').innerHTML=data.frames.map(f=>`<article class="frame" id="${f.id}"><div class="frame-title"><span class="frame-id">${f.id}</span><h3>${escape(f.headline)}</h3></div><div class="frame-body"><div class="comparison"><div class="strip">${shot(f.old,'В App Store',false)}${shot(f.previous,'Прошлый вариант',false)}${shot(f.id,'Студия',true)}</div></div><div class="feedback"><h4>Решение по ${f.id}</h4><label>Предпочтительный вариант<select data-id="${f.id}" data-field="variant"><option value="${f.id}">${f.id} — студия</option><option value="${f.previous}">${f.previous} — прошлый</option><option value="${f.old}">${f.old} — исходный</option></select></label><label>Что делаем<select data-id="${f.id}" data-field="decision"><option value="">Пока не выбрано</option>Оставить</option><option>Изменить</option><option>Убрать</option></select></label><label>Новый заголовок<input data-id="${f.id}" data-field="headline" placeholder="${escape(f.headline)}"></label><label>Новый подзаголовок<input data-id="${f.id}" data-field="subtitle" placeholder="${escape(f.subtitle)}"></label><label>Комментарий<textarea rows="3" data-id="${f.id}" data-field="comment" placeholder="Что изменить в картинке, тексте или порядке"></textarea></label><span class="hint">Выбор варианта сам по себе не означает «утверждено».</span></div></div><details class="source"><summary>Смысл, ограничения и источник</summary><p><strong>JTBD:</strong> ${escape(f.jtbd)}</p><p>${escape(f.reason)}</p><p>${escape(f.limitation)}</p><p>${escape(f.source)}</p></details></article>`).join('');
 $('#rationale').innerHTML=data.frames.map(f=>`<tr><td><strong><a href="#${f.id}">${f.id}</a> · ${escape(f.headline)}</strong>${escape(f.subtitle)}</td><td><strong>${escape(f.audience)}</strong>${escape(f.jtbd)}</td><td><strong>${escape(f.visual)}</strong>${escape(f.funnel)}</td><td>${escape(f.reason)}</td><td>${escape(f.limitation)}</td></tr>`).join('');
 $('#expert-source').innerHTML=`<p><strong>Вопрос:</strong> ${escape(data.expert.question)}</p><blockquote>${escape(data.expert.answer)}</blockquote><p><strong>Показанный фрагмент:</strong> ${escape(data.expert.excerpt)}</p><p>Источник: существующий английский ответ photo_help в ExpertSafeReplies. Для снимка используется нативный AIChatView с крупным системным текстом. Полный текст сохранён; перед вторым предложением добавлен абзац для точного кадрирования. Нового запроса к провайдеру для этого примера не выполнялось.</p>`;
 for(const el of document.querySelectorAll('[data-field]')){el.value=val(el.dataset.id,el.dataset.field)||(el.dataset.field==='variant'?el.dataset.id:'');el.addEventListener('input',()=>{const id=el.dataset.id;if(!state[id]||typeof state[id]!=='object')state[id]={};state[id][el.dataset.field]=el.value;save();});}
 for(const id of ['reviewer','order','general']){const el=$('#'+id);el.value=typeof state[id]==='string'?state[id]:'';el.addEventListener('input',()=>{state[id]=el.value;save();});}
 for(const b of document.querySelectorAll('[data-scale]'))b.addEventListener('click',()=>{document.documentElement.style.setProperty('--preview',b.dataset.scale+'px');document.querySelectorAll('[data-scale]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
 for(const b of document.querySelectorAll('[data-image]'))b.addEventListener('click',()=>{const id=b.dataset.image;const ext=id.startsWith('O')?'jpg':'png';const url=`originals/${id}.${ext}`;$('#zoom-title').textContent=id;$('#zoom-image').src=url;$('#zoom-image').alt=id+' — полный размер';$('#original').href=url;$('#download-original').href=url;$('#download-original').download=id+'.'+ext;$('#zoom').showModal();});
 $('#close-zoom').addEventListener('click',()=>$('#zoom').close());
 const exportText=()=>{const lines=['JewelSnap — решения по скриншотам','Версия: '+data.version,'Участник: '+(state.reviewer||'не указан'),'Порядок: '+(state.order||'не изменён'),''];for(const f of data.frames){lines.push(f.id+' / вариант: '+(val(f.id,'variant')||f.id),'Решение: '+(val(f.id,'decision')||'не выбрано'));for(const [k,label] of [['headline','Заголовок'],['subtitle','Подзаголовок'],['comment','Комментарий']])if(val(f.id,k))lines.push(label+': '+val(f.id,k));lines.push('');}if(state.general)lines.push('Общий комментарий:',String(state.general));return lines.join('\n');};
 const preview=()=>{const el=$('#export-text');el.hidden=false;el.value=exportText();return el;};
 $('#preview').addEventListener('click',preview);
 $('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(exportText());$('#copy-status').textContent='Скопировано. Теперь вставьте решения в переписку.';}catch{const el=preview();el.focus();el.select();$('#copy-status').textContent='Автокопирование недоступно. Скопируйте выделенный текст вручную.';}});
 $('#download').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([exportText()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='jewelsnap-decisions-'+data.version+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 save();window.reviewReady=true;
})();
